package com.lhd.HiMall.entity;

import java.util.Date;
import java.util.List;


import com.baomidou.mybatisplus.annotations.TableField;
import com.fasterxml.jackson.annotation.JsonFormat;

public class ClassificationofGoodsItem {
	
	
	
	//第一个价格
		@TableField(exist=false)
		private Double priceOne ;
		//第二个价格
		@TableField(exist=false)
		private Double priceTow ; 
		//总条数
		@TableField(exist=false)
		private long totalNum ;
		//总页数
		@TableField(exist=false)
		private Integer totalPages ; 
		
		
		private List<Imginfo> imginfos ;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.id
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cId
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cName
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.inventory
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private Double inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.images
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.price
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.orderNo
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.brand
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.createTime
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.detail
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.showStatus
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    private Integer showstatus;
    
    
    
    
    public Double getPriceOne() {
		return priceOne;
	}

	public void setPriceOne(Double priceOne) {
		this.priceOne = priceOne;
	}

	public Double getPriceTow() {
		return priceTow;
	}

	public void setPriceTow(Double priceTow) {
		this.priceTow = priceTow;
	}

	public long getTotalNum() {
		return totalNum;
	}

	public void setTotalNum(long totalNum) {
		this.totalNum = totalNum;
	}

	public Integer getTotalPages() {
		return totalPages;
	}

	public void setTotalPages(Integer totalPages) {
		this.totalPages = totalPages;
	}

	public List<Imginfo> getImginfos() {
		return imginfos;
	}

	public void setImginfos(List<Imginfo> imginfos) {
		this.imginfos = imginfos;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.id
     *
     * @return the value of classificationof_goods_item.id
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.id
     *
     * @param id the value for classificationof_goods_item.id
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cId
     *
     * @return the value of classificationof_goods_item.cId
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cId
     *
     * @param cid the value for classificationof_goods_item.cId
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cName
     *
     * @return the value of classificationof_goods_item.cName
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cName
     *
     * @param cname the value for classificationof_goods_item.cName
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.inventory
     *
     * @return the value of classificationof_goods_item.inventory
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Double getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.inventory
     *
     * @param inventory the value for classificationof_goods_item.inventory
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setInventory(Double inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.images
     *
     * @return the value of classificationof_goods_item.images
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.images
     *
     * @param images the value for classificationof_goods_item.images
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.price
     *
     * @return the value of classificationof_goods_item.price
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.price
     *
     * @param price the value for classificationof_goods_item.price
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.orderNo
     *
     * @return the value of classificationof_goods_item.orderNo
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.orderNo
     *
     * @param orderno the value for classificationof_goods_item.orderNo
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.brand
     *
     * @return the value of classificationof_goods_item.brand
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.brand
     *
     * @param brand the value for classificationof_goods_item.brand
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.createTime
     *
     * @return the value of classificationof_goods_item.createTime
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.createTime
     *
     * @param createtime the value for classificationof_goods_item.createTime
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.detail
     *
     * @return the value of classificationof_goods_item.detail
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.detail
     *
     * @param detail the value for classificationof_goods_item.detail
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.showStatus
     *
     * @return the value of classificationof_goods_item.showStatus
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public Integer getShowstatus() {
        return showstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.showStatus
     *
     * @param showstatus the value for classificationof_goods_item.showStatus
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    public void setShowstatus(Integer showstatus) {
        this.showstatus = showstatus;
    }

	@Override
	public String toString() {
		return "ClassificationofGoodsItem [priceOne=" + priceOne + ", priceTow=" + priceTow + ", totalNum=" + totalNum
				+ ", totalPages=" + totalPages + ", imginfos=" + imginfos + ", id=" + id + ", cid=" + cid + ", cname="
				+ cname + ", inventory=" + inventory + ", images=" + images + ", price=" + price + ", orderno="
				+ orderno + ", brand=" + brand + ", createtime=" + createtime + ", detail=" + detail + ", showstatus="
				+ showstatus + "]";
	}
    
    
}