package com.lhd.HiMall.entity;

public class Clothessize {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.id
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.cid
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.size
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.munbers
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private Double munbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.color
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothessize.freight
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    private Double freight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.id
     *
     * @return the value of clothessize.id
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.id
     *
     * @param id the value for clothessize.id
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.cid
     *
     * @return the value of clothessize.cid
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.cid
     *
     * @param cid the value for clothessize.cid
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.size
     *
     * @return the value of clothessize.size
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.size
     *
     * @param size the value for clothessize.size
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.munbers
     *
     * @return the value of clothessize.munbers
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public Double getMunbers() {
        return munbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.munbers
     *
     * @param munbers the value for clothessize.munbers
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setMunbers(Double munbers) {
        this.munbers = munbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.color
     *
     * @return the value of clothessize.color
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.color
     *
     * @param color the value for clothessize.color
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothessize.freight
     *
     * @return the value of clothessize.freight
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public Double getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothessize.freight
     *
     * @param freight the value for clothessize.freight
     *
     * @mbg.generated Mon Apr 06 10:14:03 CST 2020
     */
    public void setFreight(Double freight) {
        this.freight = freight;
    }

	@Override
	public String toString() {
		return "Clothessize [id=" + id + ", cid=" + cid + ", size=" + size + ", munbers=" + munbers + ", color=" + color
				+ ", freight=" + freight + "]";
	}
    
}