package com.lhd.HiMall.entity;

public class Orderlistmsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlistmsg.id
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlistmsg.rioid
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    private String rioid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlistmsg.address
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlistmsg.price
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlistmsg.id
     *
     * @return the value of orderlistmsg.id
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlistmsg.id
     *
     * @param id the value for orderlistmsg.id
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlistmsg.rioid
     *
     * @return the value of orderlistmsg.rioid
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public String getRioid() {
        return rioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlistmsg.rioid
     *
     * @param rioid the value for orderlistmsg.rioid
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public void setRioid(String rioid) {
        this.rioid = rioid == null ? null : rioid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlistmsg.address
     *
     * @return the value of orderlistmsg.address
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlistmsg.address
     *
     * @param address the value for orderlistmsg.address
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlistmsg.price
     *
     * @return the value of orderlistmsg.price
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlistmsg.price
     *
     * @param price the value for orderlistmsg.price
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}