package com.lhd.HiMall.entity;

import java.util.Date;

public class OrderList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.id
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.rioId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private String rioid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.cId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.userId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.createTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.payStatus
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.payMoney
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Double paymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.payTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.tel
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.address
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.numbers
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer numbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.userName
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.isShow
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    private Integer isshow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.id
     *
     * @return the value of order_list.id
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.id
     *
     * @param id the value for order_list.id
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.rioId
     *
     * @return the value of order_list.rioId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public String getRioid() {
        return rioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.rioId
     *
     * @param rioid the value for order_list.rioId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setRioid(String rioid) {
        this.rioid = rioid == null ? null : rioid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.cId
     *
     * @return the value of order_list.cId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.cId
     *
     * @param cid the value for order_list.cId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.userId
     *
     * @return the value of order_list.userId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.userId
     *
     * @param userid the value for order_list.userId
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.createTime
     *
     * @return the value of order_list.createTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.createTime
     *
     * @param createtime the value for order_list.createTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.payStatus
     *
     * @return the value of order_list.payStatus
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.payStatus
     *
     * @param paystatus the value for order_list.payStatus
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.payMoney
     *
     * @return the value of order_list.payMoney
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Double getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.payMoney
     *
     * @param paymoney the value for order_list.payMoney
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setPaymoney(Double paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.payTime
     *
     * @return the value of order_list.payTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.payTime
     *
     * @param paytime the value for order_list.payTime
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.tel
     *
     * @return the value of order_list.tel
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.tel
     *
     * @param tel the value for order_list.tel
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.address
     *
     * @return the value of order_list.address
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.address
     *
     * @param address the value for order_list.address
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.numbers
     *
     * @return the value of order_list.numbers
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.numbers
     *
     * @param numbers the value for order_list.numbers
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setNumbers(Integer numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.userName
     *
     * @return the value of order_list.userName
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.userName
     *
     * @param username the value for order_list.userName
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.isShow
     *
     * @return the value of order_list.isShow
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.isShow
     *
     * @param isshow the value for order_list.isShow
     *
     * @mbg.generated Tue Feb 11 13:41:02 CST 2020
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }
}