package com.lhd.HiMall.entity;

import java.util.Date;

public class SysLeavebill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.userid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.state
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.createtime
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.id
     *
     * @return the value of sys_leavebill.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.id
     *
     * @param id the value for sys_leavebill.id
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.userid
     *
     * @return the value of sys_leavebill.userid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.userid
     *
     * @param userid the value for sys_leavebill.userid
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.state
     *
     * @return the value of sys_leavebill.state
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.state
     *
     * @param state the value for sys_leavebill.state
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.createtime
     *
     * @return the value of sys_leavebill.createtime
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.createtime
     *
     * @param createtime the value for sys_leavebill.createtime
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}