package com.lhd.HiMall.entity;

public class Sysmenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.id
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.pid
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.type
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.title
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.percode
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String percode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.icon
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.href
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.target
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.open
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.ordernum
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.available
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.id
     *
     * @return the value of sysmenu.id
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.id
     *
     * @param id the value for sysmenu.id
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.pid
     *
     * @return the value of sysmenu.pid
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.pid
     *
     * @param pid the value for sysmenu.pid
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.type
     *
     * @return the value of sysmenu.type
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.type
     *
     * @param type the value for sysmenu.type
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.title
     *
     * @return the value of sysmenu.title
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.title
     *
     * @param title the value for sysmenu.title
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.percode
     *
     * @return the value of sysmenu.percode
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.percode
     *
     * @param percode the value for sysmenu.percode
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setPercode(String percode) {
        this.percode = percode == null ? null : percode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.icon
     *
     * @return the value of sysmenu.icon
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.icon
     *
     * @param icon the value for sysmenu.icon
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.href
     *
     * @return the value of sysmenu.href
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.href
     *
     * @param href the value for sysmenu.href
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.target
     *
     * @return the value of sysmenu.target
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.target
     *
     * @param target the value for sysmenu.target
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.open
     *
     * @return the value of sysmenu.open
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.open
     *
     * @param open the value for sysmenu.open
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.ordernum
     *
     * @return the value of sysmenu.ordernum
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.ordernum
     *
     * @param ordernum the value for sysmenu.ordernum
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.available
     *
     * @return the value of sysmenu.available
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.available
     *
     * @param available the value for sysmenu.available
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}