package com.lhd.HiMall.entity;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role.id
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role.name
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role.available
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    private String available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role.creatime
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    private Date creatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ role.remark
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role.id
     *
     * @return the value of sys_ role.id
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role.id
     *
     * @param id the value for sys_ role.id
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role.name
     *
     * @return the value of sys_ role.name
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role.name
     *
     * @param name the value for sys_ role.name
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role.available
     *
     * @return the value of sys_ role.available
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role.available
     *
     * @param available the value for sys_ role.available
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role.creatime
     *
     * @return the value of sys_ role.creatime
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role.creatime
     *
     * @param creatime the value for sys_ role.creatime
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ role.remark
     *
     * @return the value of sys_ role.remark
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ role.remark
     *
     * @param remark the value for sys_ role.remark
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}