package com.lhd.HiMall.entity;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.userId
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.provice
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String provice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.city
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.county
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.adre
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String adre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.tel
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.eamil
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    private String eamil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.userId
     *
     * @return the value of user_address.userId
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.userId
     *
     * @param userid the value for user_address.userId
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.provice
     *
     * @return the value of user_address.provice
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.provice
     *
     * @param provice the value for user_address.provice
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setProvice(String provice) {
        this.provice = provice == null ? null : provice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.city
     *
     * @return the value of user_address.city
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.city
     *
     * @param city the value for user_address.city
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.county
     *
     * @return the value of user_address.county
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.county
     *
     * @param county the value for user_address.county
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.adre
     *
     * @return the value of user_address.adre
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getAdre() {
        return adre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.adre
     *
     * @param adre the value for user_address.adre
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setAdre(String adre) {
        this.adre = adre == null ? null : adre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.tel
     *
     * @return the value of user_address.tel
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.tel
     *
     * @param tel the value for user_address.tel
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.eamil
     *
     * @return the value of user_address.eamil
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public String getEamil() {
        return eamil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.eamil
     *
     * @param eamil the value for user_address.eamil
     *
     * @mbg.generated Thu Apr 09 18:57:10 CST 2020
     */
    public void setEamil(String eamil) {
        this.eamil = eamil == null ? null : eamil.trim();
    }

	@Override
	public String toString() {
		return "UserAddress [id=" + id + ", userid=" + userid + ", address=" + address + ", provice=" + provice
				+ ", city=" + city + ", county=" + county + ", adre=" + adre + ", tel=" + tel + ", eamil=" + eamil
				+ "]";
	}
    
}