package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.AdminTable;
import com.lhd.HiMall.entity.AdminTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    long countByExample(AdminTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByExample(AdminTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insert(AdminTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insertSelective(AdminTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    List<AdminTable> selectByExample(AdminTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    AdminTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminTable record, @Param("example") AdminTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExample(@Param("record") AdminTable record, @Param("example") AdminTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKeySelective(AdminTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_table
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKey(AdminTable record);
}