package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.Classificationof;
import com.lhd.HiMall.entity.ClassificationofExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationofMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    long countByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insert(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insertSelective(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    List<Classificationof> selectByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    Classificationof selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") Classificationof record, @Param("example") ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExample(@Param("record") Classificationof record, @Param("example") ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKeySelective(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKey(Classificationof record);
}