package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.ClassificationofGoodsItem;
import com.lhd.HiMall.entity.ClassificationofGoodsItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationofGoodsItemMapper {
	
	
	List<ClassificationofGoodsItem> goodsItemsById (Integer id) ;
	
	List<ClassificationofGoodsItem> findShopInfoById (Integer id) ;
	
	List<ClassificationofGoodsItem>	searchByBrandsOrPrice (@Param("brand") String brand , @Param("priceOne") Integer priceOne 
							,  @Param("priceTow") Integer priceTow) ;
	
	//熱賣
	List<ClassificationofGoodsItem> hotBuy (@Param("brand") String brand , @Param("priceOne") Integer priceOne 
										,  @Param("priceTow") Integer priceTow) ;
	
	//根据收藏商品推荐   如果用户登录
	List<ClassificationofGoodsItem> findByUserid ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
									@Param("priceTow") Integer priceTow, @Param("userId") Integer userId ) ;
	
	
	
	//查找所有
	List<ClassificationofGoodsItem> selectAll ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
			@Param("priceTow") Integer priceTow) ;
	
	
	
	List<ClassificationofGoodsItem> findShopByDesc ( @Param("brand") String brand , @Param("priceOne") Integer priceOne,
			@Param("priceTow") Integer priceTow) ;
	
	//默认推荐
	
	/**
	 * 模糊查询
	 */
	List<ClassificationofGoodsItem> fuzzyQuery ( String name ) ;
	
	//根据shopTypeId 查询商品信息
	List<ClassificationofGoodsItem> querrGoodsByShopCid ( @Param("cid") Integer cid) ;
	
	//查询商品信息 根据cid查询
	List<ClassificationofGoodsItem> queryGoodsItemByCid ( @Param("cid") Integer cid ) ;
	
	
	List<ClassificationofGoodsItem> queryByTypeId ( List<Integer> id) ;
	
	//根据 品牌  价格  cid  进行查询
	List<ClassificationofGoodsItem> searchByBrandsOrPriceAndCid ( @Param("brand") String brand , @Param("priceOne") Integer priceOne
																, @Param("priceTow") Integer priceTow , @Param("cId") Integer cId ) ;
	
	
	// 根据type id查询'
	List<ClassificationofGoodsItem> queryGoodsByTypeIds ( @Param("brand") String brand , @Param("priceOne") Integer priceOne
														, @Param("priceTow") Integer priceTow ,@Param("cid") List<Integer> id) ;
	
	
	List<ClassificationofGoodsItem> searchGoodsItem ( @Param("brand") String brand ,@Param("priceOne") Integer priceOne
													, @Param("priceTow") Integer priceTow ) ;
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    long countByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int deleteByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int insert(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int insertSelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    List<ClassificationofGoodsItem> selectByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    ClassificationofGoodsItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int updateByExample(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int updateByPrimaryKeySelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Fri Feb 28 13:22:56 CST 2020
     */
    int updateByPrimaryKey(ClassificationofGoodsItem record);
}