package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.Orderlistmsg;
import com.lhd.HiMall.entity.OrderlistmsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderlistmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    long countByExample(OrderlistmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int deleteByExample(OrderlistmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int insert(Orderlistmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int insertSelective(Orderlistmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    List<Orderlistmsg> selectByExample(OrderlistmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    Orderlistmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Orderlistmsg record, @Param("example") OrderlistmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int updateByExample(@Param("record") Orderlistmsg record, @Param("example") OrderlistmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int updateByPrimaryKeySelective(Orderlistmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlistmsg
     *
     * @mbg.generated Wed Apr 08 11:43:32 CST 2020
     */
    int updateByPrimaryKey(Orderlistmsg record);
}