package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.SysLogInfo;
import com.lhd.HiMall.entity.SysLogInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    long countByExample(SysLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByExample(SysLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insert(SysLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insertSelective(SysLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    List<SysLogInfo> selectByExample(SysLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    SysLogInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysLogInfo record, @Param("example") SysLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExample(@Param("record") SysLogInfo record, @Param("example") SysLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKeySelective(SysLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_info
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKey(SysLogInfo record);
}