package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.Sysmenu;
import com.lhd.HiMall.entity.SysmenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    long countByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int deleteByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int insert(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int insertSelective(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    List<Sysmenu> selectByExample(SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    Sysmenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sysmenu record, @Param("example") SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int updateByExample(@Param("record") Sysmenu record, @Param("example") SysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int updateByPrimaryKeySelective(Sysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmenu
     *
     * @mbg.generated Sat Feb 08 12:48:39 CST 2020
     */
    int updateByPrimaryKey(Sysmenu record);
}