package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.SysPermission;
import com.lhd.HiMall.entity.SysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    long countByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    List<SysPermission> selectByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    SysPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByExample(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ permission
     *
     * @mbg.generated Fri Feb 14 21:10:03 CST 2020
     */
    int updateByPrimaryKey(SysPermission record);
}