package com.lhd.HiMall.dao;

import com.lhd.HiMall.entity.SysRole;
import com.lhd.HiMall.entity.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    long countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    SysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ role
     *
     * @mbg.generated Sat Feb 22 13:56:36 CST 2020
     */
    int updateByPrimaryKey(SysRole record);
}